# Generated by Django 4.1.13 on 2024-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Item_images/', verbose_name='รูปภาพ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='จำนวน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่เพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาที่อัปเดต')),
            ],
        ),
    ]
