# Generated by Django 4.1.13 on 2024-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=50, verbose_name='อีเมล'),
        ),
    ]
