# Generated by Django 4.1.13 on 2024-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=50, null=True, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(max_length=100, null=True, verbose_name='คณะ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_student',
            field=models.CharField(max_length=11, null=True, verbose_name='รหัสนักศึกษา'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefix',
            field=models.CharField(max_length=100, null=True, verbose_name='คำนำหน้า'),
        ),
    ]
