# Generated by Django 4.1.13 on 2024-01-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0004_alter_userprofile_email_alter_userprofile_faculty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
