# Generated by Django 4.1.13 on 2024-01-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
