# Generated by Django 4.1.13 on 2024-01-27 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maindemo', '0007_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100, null=True, verbose_name='คำนำหน้า')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='นามสกุล')),
                ('email', models.EmailField(default='user@example.com', max_length=50, null=True, verbose_name='อีเมล')),
                ('id_student', models.CharField(max_length=11, null=True, verbose_name='รหัสนักศึกษา')),
                ('faculty', models.CharField(max_length=100, null=True, verbose_name='คณะ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
