# Generated by Django 4.1.13 on 2024-02-13 15:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maindemo', '0010_item_max_borrow_time_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 13, 15, 19, 23, 643274, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยืม')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนที่ยืม')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('borrowed', 'กำลังยืม'), ('returned', 'คืนแล้ว')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maindemo.item', verbose_name='อุปกรณ์')),
            ],
        ),
    ]
