# Generated by Django 4.1.13 on 2024-02-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0011_userprofile_created_at_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maindemo.userprofile', verbose_name='ผู้ยืม'),
        ),
    ]
