# Generated by Django 4.1.13 on 2024-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0013_alter_borrowrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('waiting', 'รออนุมัติ'), ('borrowing', 'กำลังยืม'), ('returned', 'คืนแล้ว'), ('cencel', 'ยกเลิก')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
    ]
