# Generated by Django 4.1.13 on 2024-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindemo', '0016_alter_borrowrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('waiting', 'รออนุมัติ'), ('borrowing', 'กำลังยืม'), ('returned', 'คืนแล้ว'), ('cancel', 'ยกเลิก'), ('notreturn', 'ไม่คืนของ')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
    ]
